public enum LedgeProbeFailure
{
    None,
    NotInitialized,
    NoFrontWall,
    NoTopSurface,
    UnsupportedLayer,
    TriggerSurface,
    UnsupportedRigidbodySurface,
    HeightOutOfRange,
    PreCatchHeight,
    SurfaceTooSteep,
    SurfaceHeightMismatch,
    UnsupportedGap,
    AmbiguousGeometry,
    CatchBlocked,
    CrestBlocked,
    StandingBlocked,
    CorridorBlocked,
    RestrictedVolume,
    TargetInvalid
}
