public enum SceneTransitionTraceMarker
{
    RequestReceived,
    RequestAccepted,
    RequestRejectedAlreadyTransitioning,
    ControlLocked,
    CameraFreezeRequested,
    FadeOutStarted,
    FadeOutComplete,
    SceneLoadStarted,
    SceneLoaded,
    DestinationResolved,
    HeroPlaced,
    CameraRebindStarted,
    CameraRebindComplete,
    FadeInStarted,
    FadeInComplete,
    EntryMotionStarted,
    EntryMotionComplete,
    GameplayRestored,
    TransitionFailed,
    CleanupComplete
}
